### ISSUE TITLE
Enhancment request, Red highlight for type syntax errors

### ISSUE THREAD

**Issue by GuyKroizman** [cespare/vim-toml#46]
When I open a toml file in (ubuntu's) gedit which has
```A = True```
or
```A = SOCKET_STREAM```

both True and SOCKET_STREAM will be highlighted red because they are not valid values.
It would be great if we could have this too.

**Comment by cespare** [comment]
Closing this since I don't have plans to implement it, and because (per my previous comment) I'm personally not a fan of disruptive error highlighting. For example, in recent versions of vim I've found that I need to use

    let g:vim_json_warnings = 0

to avoid annoying error highlighting in JSON files.

I'm still open to a PR here as long as it either can't have false positives (including the case I mentioned above) or else is hidden behind an option that is off by default.
